config/routes.rb
Rails.application.routes.draw do
 get '/assignDrone/:id' , to: "orderdetails#assignDrone", as: "button"

  resources :people
  resources :orders
  resources :orderdetails 
  	
  resources :products
  resources :drones
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end
 

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
  belongs_to :order
  belongs_to :product  
end

app/controllers/orderdetails_controller.rb
class OrderdetailsController < ApplicationController
  before_action :set_orderdetail, only: [:show, :edit, :update, :destroy]

  # GET /orderdetails
  # GET /orderdetails.json
  def index
    @orderdetails = Orderdetail.all
    @drones = Drone.all
    @people = Person.all
    @products = Product.all

  end

  # GET /orderdetails/1
  # GET /orderdetails/1.json
  def show
  end

  # GET /orderdetails/new
  def new
    @orderdetail = Orderdetail.new
  end

  # GET /orderdetails/1/edit
  def edit
  end

  # POST /orderdetails
  # POST /orderdetails.json
  def create

     @order = Order.new(:drone_id => Drone.where('name = :dname', dname: 'No Drone Assigned').first.id, :person_id => params[:orderdetail][:person_id], :status => 1)
     if @order.save
        @orderdetail =  Orderdetail.new(:product_id => params[:orderdetail][:product_id],:quantity => params[:orderdetail][:quantity],:order_id => @order.id)
     
        respond_to do |format|
        if @orderdetail.save
           format.html { redirect_to @orderdetail, notice: 'Orderdetail was successfully created.' }
            format.json { render :show, status: :created, location: @orderdetail }
        else
        format.html { render :new }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /orderdetails/1
  # PATCH/PUT /orderdetails/1.json
  def update
    respond_to do |format|
      if @orderdetail.update(orderdetail_params)
        format.html { redirect_to @orderdetail, notice: 'Orderdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @orderdetail }
      else
        format.html { render :edit }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderdetails/1
  # DELETE /orderdetails/1.json
  def destroy
    @orderdetail.destroy
    @order = Order.find(@orderdetail.order_id)
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orderdetails_url, notice: 'Orderdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  #GET /drones
   def assignDrone
    @drone = Drone.find(params[:id])
    @order = Order.where('status = :dstatus', dstatus: 1).first
    
    respond_to do |format|
      format.html { redirect_to orderdetails_url}
      format.json { head :no_content }
    end

   if(@order)
       Thread.new do
         @drone.status = 2
         @drone.save

         if @drone.status = 2
            sleep(8)
            @drone.status = 3
            @drone.save
            7
            @order.status = 2
            @order.drone_id = @drone.id
            @order.save

          end
          if @drone.status = 3
            sleep(8)
            @drone.status = 4
            @drone.save

           end
          
          if @drone.status = 4
            sleep(8)
            @drone.status = 5
            @drone.save
            @order.status = 3
            @order.save
        end
          
          if @drone.status = 5
            sleep(8)
            @drone.status = 6
            @drone.save
        
          end
          if @drone.status = 6
            sleep(8)
            @drone.status = 7
            @drone.save
              
          end
          if @drone.status = 7
            sleep(8)
            @drone.status = 1
            @drone.save
        end

        
       end
   end
 end
    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderdetail
      @orderdetail = Orderdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orderdetail_params
      params.require(:orderdetail).permit(:person_id, :product_id, :quantity)

    end

end

app/helpers/orderdetails_helper.rb
module OrderdetailsHelper
end

app/views/orderdetails/_form.html.erb
<%= form_with(model: orderdetail, local: true) do |form| %>
  <% if orderdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orderdetail.errors.count, "error") %> prohibited this orderdetail from being saved:</h2>

      <ul>
      <% orderdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <!-- <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id, id: :orderdetail_order_id %>
  </div> 

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :orderdetail_product_id %>
  </div>  -->
  
  <div class="field">
  <%= form.select :product_id, Product.all.collect {|p| [ p.name, p.id] }, { :include_blank => "Please select a product" }, id: :orderdetail_product_id %>
  </div>

  <div class="field">
  <%= form.select :person_id, Person.all.collect {|p| [ p.name, p.id] }, { :include_blank => "Registered User" }, id: :orderdetail_person_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :orderdetail_quantity %>
  </div> 

  <div class="actions">
    <%= form.submit %>

  </div>
<% end %>
 

app/views/orderdetails/edit.html.erb
<h1>Editing Orderdetail</h1>

<%= render 'form', orderdetail: @orderdetail %>

<%= link_to 'Show', @orderdetail %> |
<%= link_to 'Back', orderdetails_path %>

app/views/orderdetails/index.html.erb
<html>
<p id="notice"><%= notice %></p>

<body class="wrapper" onload="polling()">

  <font size="7" color="SeaGreen" align="center">Order/Drone Assignment Portal</font>
  <br><br><br><br>

  <font size="6" color="teal">Orderdetails</font>
  
        <table class="table">
          <thead>
              <tr class="row header green">
                  
                  <th class="cell">Customer</th>
                  <th class="cell">Product</th>
                  <th class="cell">Quantity</th>
                  <th class="cell">Status</th>
                  <th class="cell">Drone</th>
                  <th class="cell" colspan="3"></th>
                
                </tr>
            
          </thead>

          <tbody>
            <% @orderdetails.each do |orderdetail| %>
              <tr class="row">
                <td class="cell"><%= orderdetail.order.person.name %></td>
                <td class="cell"><%= orderdetail.product.name %></td>
                <td class="cell"><%= orderdetail.quantity %></td>
                <td class="cell"><%= 
                case orderdetail.order.status  
                  when 1
                     "Order Placed"
                  when 2
                     "Dispatched/In Transit"
                  when 3
                     "Delivered"
                  else
                    "Unknown Status"
                    end%></td>
                <td class="cell"><%= orderdetail.order.drone.name %></td>
                <td class="cell"><%= link_to 'Show', orderdetail %></td>
                <td class="cell"><%= link_to 'Edit', edit_orderdetail_path(orderdetail) %></td>
                <td class="cell"><%= link_to 'Destroy', orderdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>
    
       <%= link_to 'Place a new Order by clicking here', new_orderdetail_path %>

        <br/>
        <br/>
        <font size="6" color="teal">Drones</font>

        <table class="table">
          <thead>
            <tr class="row header green">
              <th class="cell">Status</th>
              <th class="cell">Name</th>
              <th class="cell" colspan="4"></th>
            </tr>
          </thead>

          <tbody>
            <% @drones.each do |drone| %>
              <tr class="row">
                <td class="cell">
                  <%= if drone.name != "No Drone Assigned"
                        
                      case drone.status 
                      when 1
                         "Idle"
                      when 2
                         "Assigned"
                      when 3
                         "Picked up enroute"
                      when 4
                         "Reached"
                      when 5
                         "Delivered"
                      when 6
                         "Way Back"
                      when 7
                         "Reached Hub"
                      else
                        "Unknown Status"
                      end
                end%></td>
                <td class="cell">
                  <%= if drone.name != "No Drone Assigned"
                      drone.name
                     end%>
                  </td>
                <td class="cell">
                  <%= if drone.name != "No Drone Assigned"
                      link_to 'Show', drone
                   end%></td>
                <td class="cell">
                  <%= if drone.name != "No Drone Assigned" 
                      link_to 'Edit', edit_drone_path(drone) 
                      end%></td>
                <td class="cell">
                  <%= if drone.name != "No Drone Assigned"  
                  link_to 'Destroy', drone, method: :delete, data: { confirm: 'Are you sure?' } 
                  end%></td>
                  <td class="cell"><%= if drone.name != "No Drone Assigned"

                    button_to "Assign Drone", "/assignDrone/#{drone.id}" , method: :get 
                   
                    end%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      

        <br>


        <%= link_to 'A new drone can be added from here', new_drone_path %>

        <script>
        function polling() {
            //alert("Page is loaded");
            sleep(8050)
             //alert("Page is loadedafter sleep");
            window.location.reload(true);
        }
        function sleep(milliseconds) {
          var start = new Date().getTime();
          for (var i = 0; i < 1e7; i++) {
            if ((new Date().getTime() - start) > milliseconds){
              break;
            }
          }
        }
        </script>

      </br>
    </br>

        <font size="6" color="teal">Customer Registration</font>

   
        <table class="table">
          <thead>
            <tr class="row header green">
              <th class="cell">Name</th>
              <th class="cell">Phonenumber</th>
              <th class="cell">Address</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @people.each do |person| %>
              <tr class="row">
                <td class="cell"><%= person.name %></td>
                <td class="cell"><%= person.phonenumber %></td>
                <td class="cell"><%= person.address %></td>
                <td class="cell"><%= link_to 'Show', person %></td>
                <td class="cell"><%= link_to 'Edit', edit_person_path(person) %></td>
                <td class="cell"><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>
    
        <%= link_to 'New Person Registration link', new_person_path %>
        <br/>
        <br/>

        <font size="6" color="teal">Products(To be added by the store employee)</font>
   
        <table class="table">
          <thead>
            <tr class="row header green">
              <th class="cell">Name</th>
              <th class="cell">Category</th>
              <th class="cell" colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @products.each do |product| %>
              <tr class="row">
                <td class="cell"><%= product.name %></td>
                <td class="cell"><%= product.category %></td>
                <td class="cell"><%= link_to 'Show', product %></td>
                <td class="cell"><%= link_to 'Edit', edit_product_path(product) %></td>
                <td class="cell"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    
        <br>

        <%= link_to 'A New Product can be added here', new_product_path %>
</body>
</html>

app/views/orderdetails/new.html.erb
<h1>New Orderdetail</h1>

<%= render 'form', orderdetail: @orderdetail %>

<%= link_to 'Back', orderdetails_path %>

app/views/orderdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @orderdetail.order.person.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @orderdetail.product.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @orderdetail.quantity %>
</p>

<%= link_to 'Edit', edit_orderdetail_path(@orderdetail) %> |
<%= link_to 'Back', orderdetails_path %>